# I manually switch between the two :P
# theme = "flexoki_light"
theme = "carbonfox"

[editor]
color-modes = true
true-color = true
bufferline = "multiple"
idle-timeout = 10
cursorline = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.statusline]
left = [
    "mode",
    "spinner",
    "file-name",
    "file-modification-indicator",
    "spacer",
    "diagnostics",
]
right = ["version-control", "selections", "position", "file-encoding"]

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[keys.normal]
"A-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-up" = [
    "extend_to_line_bounds",
    "delete_selection",
    "move_line_up",
    "paste_before",
]
