[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "markdown"
rulers = [80]

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rs|rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
shebangs = ["rust-script", "cargo"]
auto-format = false
comment-tokens = ["//", "///", "//!"]
block-comment-tokens = [
  { start = "/*", end = "*/" },
  { start = "/**", end = "*/" },
  { start = "/*!", end = "*/" },
]
formatter = { command = "rustfmt" }
language-servers = ["rust-analyzer"]
indent = { tab-width = 4, unit = "    " }
persistent-diagnostic-sources = ["rustc", "clippy"]
rulers = [100]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config]
basedpyright.analysis.diagnosticMode = "openFilesOnly"

[language-server.ruff]
command = "uv"
args = ["run", "ruff", "server"]

[[language]]
name = "python"
rulers = [88]
language-servers = ["basedpyright", "ruff"]
auto-format = false
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", ".pythonrc"]
roots = ["setup.py", "setup.cfg", "pyproject.toml", "."]
comment-token = "#"

[language.formatter]
command = "uv"
args = ["run", "ruff", "format", "-q", "-"]

[language.indent]
tab-width = 4
unit = "    "
